### ISSUE TITLE
don't require .cs50.yml in debug mode?

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#118]
Use case is wanting to run some checks for a lab without giving the lab a public slug (as would happen by creating a `check50` key in `.cs50.yml`). Could we assume that the check should be run on the entire contents of `$CWD`?

```
~/workspace/tmp/ (v3dev) $ check50 -d .
/home/ubuntu/workspace/tmp/.cs50.yaml not found
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.0/bin/check50", line 11, in <module>
    load_entry_point('check50==3.0.0', 'console_scripts', 'check50')()
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/check50/__main__.py", line 230, in main
    config = internal.load_config(internal.check_dir)
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/check50/internal.py", line 71, in load_config
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/workspace/tmp/.cs50.yaml
```

**Comment by crossroads1112** [comment]
`.cs50.yaml` is currently required (and I think should remain so) for a couple of reasons: 

1. If it works in dev mode, it should work once pushed to GitHub. We shouldn't force you to name your checks file `__init__.py` if you want to use dev mode when this is configurable in `.cs50.yaml`. Nor should we prevent you from using your translations in dev mode

2. This prevents people from accidentally forgetting `.cs50.yaml` 

3. If you don't want it to be available publically, don't push it to GitHub.

**Comment by dmalan** [comment]
Hm, few follow-ups:

1. What keys are required in `.cs50.yml` for localization?
1. Does `check50` respect `!include`, `!exclude`, and `!require` in `--local` and `--dev` modes, such that a subset of the contents of `$CWD` are copied to a temp directory before `check50` is run?

**Comment by Jelleas** [comment]
2. Yup `check50` does that via `lib50`. We call `lib50.files()` and `lib50.working_area()` when running locally. Effectively using the same logic as when we're pushing to git via lib50.

See: https://github.com/cs50/check50/blob/fff25045caeee995dcd685a8c8533d590cc2b2c9/check50/__main__.py#L240

**Comment by dmalan** [comment]
2. Okay, that's pretty compelling then.

**Comment by crossroads1112** [comment]
1. minimally `translations: true` which is identical to 

```
translations:
  localedir: locale
  domain: messages
```
