### ISSUE TITLE
add check.bash extension that parses a .bash_history file?

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#120]
Use case is to check whether a student ran one or more commands, as in a Linux lab. Would be ideal if history file also reported CWD after each command.

**Comment by crossroads1112** [comment]
Not really sure this is worth putting in the default API since it is so niche, but could be implemented as an extension.

**Comment by crossroads1112** [comment]
Actually, this is almost certainly too niche since it would need to rely on assumptions about the environment (like that the CWD was recorded in ".bash_history"). I don't think this belongs in `check50`, though could be implemented as a labs-specific extension.
