### ISSUE TITLE
dict-based checks should probably be written to a temp directory?

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#123]
Are they currently being written to the cloned directory? If so, what if an author has an `__init__.py` already there but is experimenting in dev mode with `dict`-based checks?

https://github.com/cs50/check50/blob/v3dev/check50/internal.py#L82-L85

**Comment by crossroads1112** [comment]
This is intentional. This way someone writing simple checks immediately has a Python version of their checks that they could use simply by changing the `checks` key in their `.cs50.yaml`. If they already have an `__init__.py` there isn't really any reason for them to be using the yaml checks.

**Comment by dmalan** [comment]
But they're then likely to check that dynamically created `__init__.py` into their repo (accidentally), no, when developing/testing locally? In which case it might now be ambiguous/confusing which checks are actually running if they make changes to the YAML and/or `__init__.py`? Would seem cleaner to add a flag to `check50` that generates `__init__.py` only on demand, a la `check50 --convert .cs50.yaml __init__.py` or such, and then when this is happening behind the scenes, indeed output the latter to a temp dir?

**Comment by dmalan** [comment]
But there's still the case of accidentally clobbering one's existing `__init__.py`. E.g., if a teacher writes some YAML-based checks, runs them, thereby generating `__init__.py`, then makes manual changes to the latter, forgetting to change `.cs50.yaml` to point to that file, they've just clobbered their changes. I do think outputting of an artifact should be opt-in, else it's a surprise, documentation or otherwise. What about just adding, e.g., a `-y` flag or such that indicates "output `__init__.py` for YAML-based checks", which enables generation of the artifact in `$CWD`, else it's put in a temp directory?

**Comment by crossroads1112** [comment]
I don't think this makes any sense as an argument to check50 since it only makes sense in dev mode anyway and would be kinda confusing to the vastly larger user base that don't write these checks. If anything it just belongs as a console script. Would renaming an existing `__init__.py` to something else instead of overwriting it address your concern?

**Comment by Jelleas** [comment]
We could check for a diff if we are compiling compiling from `.yaml` to `.py`. Such that if `__init__.py` exists, we check if our newly compiled `.yaml` checks cause any changes, if so, warn the user with a y/n prompt, then overwrite. This way you only get the prompt when developing, and don't unexpectedly get your files clobbered.

**Comment by dmalan** [comment]
> We could check for a diff...

Okay, this approach sounds good. That way, no work is lost. Though I do suspect we'll end up in a situation where folks will have YAML checks and functionally equivalent `__init__.py` files in their repo. Are we sure we want to promote such?

**Comment by crossroads1112** [comment]
This does mean that if a teacher did leave a `.cs50.yaml` file whose checks differed from an `__init__.py` in the same directory, all of their students would get this prompt. Should probably only warn in dev mode?

**Comment by Aabhusan** [comment]
I am getting issue. With installing flask in Windows. Please anyone help me as soon as possible.
