### ISSUE TITLE
rename status: to passed:?

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#126]
Then the semantics of a line like `if results[0].passed` would reflect the question being asked better than `if results[0].status`.

CC @brianyu28

**Comment by crossroads1112** [comment]
The state is ternary though, and "passed" sounds like a binary. Don't love status either but I don't think "passed" is quite right.

**Comment by tlively** [comment]
I strongly support this change for uses I’ve seen but am missing some context. What are the three possible states?

**Comment by dmalan** [comment]
* `true` == check ran and passed
* `false` == check ran and failed
* `null` == check didn't run because a dependency failed

**Comment by crossroads1112** [comment]
`null` == check didn't run because a dependency failed OR there was an error executing the checked.

**Comment by crossroads1112** [comment]
d21ee40
