### ISSUE TITLE
review JSON output

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#13]
@brianyu28, mind pasting a sample JSON output object here (that has some to-be green, red, and yellow results)?

**Comment by brianyu28** [comment]
```
$ python check50.py -d water water.c
{"exists": true, "test_reject_foo": true, "compiles": true, "test2": true, "test1": true, "test10": true, "test5": true, "test_reject_123abc": true, "test_reject_empty": true}
```

**Comment by brianyu28** [comment]
And when not everything passes:

```
$ python check50.py -d water water.c
{"test1": null, "test2": null, "test_reject_foo": null, "test10": null, "test_reject_empty": null, "test_reject_123abc": null, "test5": null, "exists": true, "compiles": false}
```

**Comment by dmalan** [comment]
Does the JSON not contain `rationale` and logging too?

**Comment by brianyu28** [comment]
My original thinking was that the JSON was only for sending data to CS50.me, in which case it just needed the test results? But can also add `rationale` and `log` if desirable.

**Comment by dmalan** [comment]
Hm, do we need to ask Anna if there's an out-of-band way of recording the log and rationales, if not in stdout of the Travis log? That might nudge this one way or the other.

**Comment by brianyu28** [comment]
Don't we want the rationale/log in the Travis stdout?

**Comment by crossroads1112** [comment]
Closing this, per our discussions on the v3 json.
