### ISSUE TITLE
valgrind throttling

### ISSUE THREAD

**Issue by kzidane** [cs50/check50#139]
@dmalan @crossroads1112 @Jelleas @brianyu28 

Not sure if this is fixed in v3 or if it needs a fix at all, but for the speller challenge now, the `spawn` calls in the "qualifies for Big Board" check implicitly call `valgrind` because of the `@valgrind` decorator and we're throttling these calls, expecting them to run for 20-ish seconds at most. A problem with that is that even if student's code runs fast (e.g., takes a second) , `valgrind` might still take longer than 20 (e.g., if student's calling `malloc` too many times). Do we think it's reasonable to consider `valgrind`'s runtime for the challenge?

**Comment by crossroads1112** [comment]
This isn't really a check50 issue so much as it is an issue with the check. We can set this timeout as needed. I've increased the timeout to 60 seconds in cs50/problems for v3. I can do the same for cs50/checks if necessary.
