### ISSUE TITLE
InvalidSlugError on connection timeout

### ISSUE THREAD

**Issue by Qvdpost** [cs50/check50#140]
When on a bad/broken internet connection check50 throws an InvalidSlugError because git ls-remote times out. Which is confusing since the slug is actually valid.

Using --offline fixes it, so perhaps it would be useful to suggest the user to run check50 with the --offline flag?

Current output:
```
INFO:lib50.api:command git ls-remote --heads https://github.com/qvdpost/cs50x timed out
Invalid slug qvdpost/cs50x/master/adventure/check50/crowther
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/bin/check50", line 11, in <module>
    load_entry_point('check50==3.0.0', 'console_scripts', 'check50')()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/check50/__main__.py", line 246, in main
    internal.check_dir = lib50.local(args.slug, "check50", offline=args.offline)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/lib50/api.py", line 66, in local
    slug = Slug(slug, offline=offline)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/lib50/api.py", line 388, in __init__
    raise InvalidSlugError(_("Invalid slug {}".format(slug)))
lib50.errors.InvalidSlugError: Invalid slug qvdpost/cs50x/master/adventure/check50/crowther
```

**Comment by crossroads1112** [comment]
I don't think we can unilaterally say "use offline mode" because offline mode won't work e.g. the first time you use check50. Ideally we'd throw an error more along the lines of "could not connect to GitHub" but unfortunately our Git API is pretty monolithic and doesn't really distinguish between those two cases super well. Will give some more thought here.

**Comment by Jelleas** [comment]
Implemented in https://github.com/cs50/check50/commit/da7c9f0e88da226c89d5f7c418ff1be464a33e17
