### ISSUE TITLE
Slug suggestions

### ISSUE THREAD

**Issue by Jelleas** [cs50/check50#142]
I often find myself and students misremembering slugs. Especially when checks are split into two (or more):

```
cs50/problems/2018/x/mario/less
cs50/problems/2018/x/mario/more
```

Running:

```
check50 cs50/problems/2018/x/mario
```

Only throws an invalid slug error. 

Maybe we could try and suggest some likely valid slugs. i.e. direct extensions (in the <path> part of the slug>)?

**Comment by crossroads1112** [comment]
Done
