### ISSUE TITLE
require user to specify output directory with -o/--output, just like render50

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#150]

**Comment by crossroads1112** [comment]
`-o` is already used to mean the 'output format' (ansi vs json). style50 takes `-o` to mean the same thing (e.g. 'split' vs 'unified' etc.) so both would need to be changed if consistency with render50 is required. I've added a `--output-file` to check50 in the meantime. This is similar in style to what valgrind does with `--log-file` and `--xml-file`.
