### ISSUE TITLE
can max_workers potentially cause a deadlock?

### ISSUE THREAD

**Issue by kzidane** [cs50/check50#171]
I guess if you run checks from the leaves up then this shouldn't be a problem? Just to double-check though, if we for example set max workers to 2 and there's tasks a, b, and c such that a depends on b and b depends on c. If a starts, takes a worker, then since it depends on b, b starts, takes the other worker, but since b depends on c and there are no more workers so that would be a deadlock.

**Comment by Jelleas** [comment]
Nope, `CHECK50_WORKERS` cannot cause a deadlock.

`check50 v3` ensures that each check has only one dependency and that there are no circular dependencies. With these restrictions we create a directional graph of checks to their dependents (tree-like shape graph). In your example that would be:

```
a -> b -> c
```

check50 starts with all checks that have no dependencies, that is just `a` here. Then when `a` passes, check50 will run all dependents, just `b` here. Once `b` passes, `c` will run. 

Note that the graph can be more complex such as:

```
exists -> compiles -> a -> c
                 \
                  v
                   b -> d
```
