### ISSUE TITLE
use bs4 alternative since it's no longer maintained

### ISSUE THREAD

**Issue by kzidane** [cs50/check50#190]
[Last release was in 2016 ](https://pypi.org/project/bs4/#history) and just had to monkey patch it to fix a `DeprecationWarning`.

https://github.com/cs50/baseimage/pull/52

**Comment by brianyu28** [comment]
I don't know if it's a drop-in replacement, but there's https://pypi.org/project/beautifulsoup4/ ?

**Comment by kzidane** [comment]
Ohhh I think that's the same package. It appears `bs4` just requires `beautifulsoup4`. Alright, I guess we'll just monkey patch it until they release a new version.
