### ISSUE TITLE
"timed out while waiting for program to exit" while my program runs fine on cs50 IDE

### ISSUE THREAD

**Issue by sayyedgauss** [cs50/check50#232]
I just finished working on **pset2/substitution** and the program runs fine on the cs50 IDE.
But when i run it through check50, it gives timeout error on the very last check. 
When i run it normally on the IDE, with the input given by check50 (during the last check) it works fine, prints and error text, returns 1 to the main, and exits...

Following is a screenshot of the terminal. Please suggest what can be done...

![image](https://user-images.githubusercontent.com/68429945/89119802-9cf6e880-d4ce-11ea-9bcf-90d9dfc9c548.png)

**Comment by curiouskiwi** [comment]
Your code does not recognize `BBCCEFGHIJKLMNOPQRSTUVWXYZ`  as an invalid key.  (The test you've shown above includes the ellipsis that check50 shows at the end of every test).

**Comment by sayyedgauss** [comment]
Got it!!
Silly Mistake i did while copying the input 

Thanks...
