### ISSUE TITLE
Running check 50 locally seems to return different results than when it uploads

### ISSUE THREAD

**Issue by alexhernandez** [cs50/check50#236]
check50 seems to return different outputs when run locally vs uploading.

I was working on the caesar project and ran into this issue:
When check50 locally to test my code all my tests pass, but when i use the non -l version that uploads to github I have 2 tests that fail.

<img width="1792" alt="Screen Shot 2020-12-05 at 7 26 40 PM" src="https://user-images.githubusercontent.com/2424355/101270715-a8824680-3730-11eb-918f-897f6ad255c7.png">

**Comment by Jelleas** [comment]
Hi Alex, thanks for the report! What you're seeing here is your code running on two different machines and producing different output. This is a real world problem and typically the result of code with undefined behavior. That is to say code for which it is not defined what it should do, and that then might produce different results when running on different machines or just at different times.

Say for instance one defines a variable in C without initializing that variable:

```C
int foo;
```

The programming C doesn't specify what the value of `foo` above should be. So if the code ends up printing the value of `foo`:

```C
printf("%d", foo);
```

You are likely to see different values on different machines. It could be `0`, but also  `12598943`, who knows! 

This is a very common mistake to make in a programming language like C, and also one of the primary motivators to disallow declaration without initialization in other programming languages. Odds are, given the assignment caesar, that your code might contain this same bug. Where there is a variable that your code uses in some way, but isn't fully initialized. Especially when working with `string`s a very common mistake is to omit the `\0` at the very end of the string, thus leaving it undefined as to where that string ends. Do just take a moment to double check! :)
