### ISSUE TITLE
check50 not accepting access tokens

### ISSUE THREAD

**Issue by subtra3t** [cs50/check50#239]
So, recently, I created a Personal Access Token after receiving an email from GitHub (you must also have received it if you logged into GitHub on the command line). And it works perfectly well, especially when `git push`ing to GitHub. But when I tried to log in to check50 using my Personal Access Token, it raised an error saying that my password was incorrect, and that if I used 2 factor authentication (which I don't) , I should enter my token. Does this mean that check50 doesn't use HTTPS (since tokens only work on HTTPS operations)?

**Comment by subtra3t** [comment]
Also, when I tried to log in via my account password, I could log in without any problems.

**Comment by tommylenz** [comment]
So just to make clear, if you `git push` from any project, you are using your PAT instead of your password, but `submit50` works with neither your password, nor your PAT?

**Comment by subtra3t** [comment]
> So just to make clear, if you `git push` from any project, you are using your PAT instead of your password, but `submit50` works with neither your password, nor your PAT?

@tommylenz No, it works with my password, but not with my access token. And when I push to remote git repos, I use my token with no problem.

**Comment by tommylenz** [comment]
CS50's submit tool is designed to use your password - it only uses your PAT if you are using 2FA. Do you mind using your password if it works fine?

**Comment by subtra3t** [comment]
Its okay, but after [August 2021](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/), GitHub will no longer accept account passwords to log in on the command line.

**Comment by tommylenz** [comment]
I saw this blog post as well. We should further investigate into your problem, because I can use submit50 with a PAT from this account (2FA turned on) as well as a second account (with 2FA turned off). Are you using CS50's IDE or are you working in your own environment?

**Comment by subtra3t** [comment]
I am using the [CS50 IDE](https://ide.cs50.io), **without 2 factor authentication**.

**Comment by subtra3t** [comment]
I can use tokens for CS50x 2021!
SO now I am closing this issue
