### ISSUE TITLE
slug error (lab2)

### ISSUE THREAD

**Issue by Mojo17ac** [cs50/check50#257]
Hey Guys, 

I can´t find my way through this error message when I am trying to check and submit my code: 
check50: error: the following arguments are required: slug

Everything else is working correct. I have written the code in the same ide.cs50 as I did for the prev. labs.

Any ideas on how to solve this or even what it actually means? :)

**Comment by dmalan** [comment]
Be sure to submit using precisely the `check50` command in the lab's instructions!
