### ISSUE TITLE
error in check50

### ISSUE THREAD

**Issue by SoumilGupta201** [cs50/check50#263]
i was trying to submit caesar, and while compiling on my own and checking the situations given in both check50 and submit it works perfectly fine. but while submitting it has some error
![Screenshot (26)](https://user-images.githubusercontent.com/85157550/124075128-088c6180-da62-11eb-84ec-61ca73c9d929.png)
![Screenshot (27)](https://user-images.githubusercontent.com/85157550/124075132-0a562500-da62-11eb-94bc-a5b1c23c25f5.png)
(screenshots for proof)

**Comment by rongxin-liu** [comment]
Looking at the screenshots, check50 is working fine. Please continue improving your codes until you have passed all the checks.

**Comment by tommylenz** [comment]
@SoumilGupta201 if you read the checks carefully, check50 tells you what's wrong! In this case it's "expected exit code 0,  not 1", which means that your program exits with code 1 but should exit with code 0 if encryption was successful. Recall that the exit code tells the user (or other programs) whether the given task could be executed successfully. If your program encrypts correctly, it should also exit with the correct code. Try fixing that! :)
