### ISSUE TITLE
Can't execute check50 cs50/problems/2021/x/mario/less

### ISSUE THREAD

**Issue by rebecachito** [cs50/check50#270]
When I try to execute it, it asks to: Enter passphrase for SSH key, and I do because I just created it, and it returns this: Make sure your username and/or personal access token are valid and check50 is enabled for your account. To enable check50, please go to https://submit.cs50.io in your web browser and try again. For instructions on how to set up a personal access token, please visit https://cs50.ly/github

If I type something else it says: Looks like that passphrase is incorrect, trying authentication with username and Personal Access Token instead.
Enter username for GitHub

I enabled check50 for my account, I enabled the two factor authentication and created a personal access token

I enter username and personal access token and I get this again: You might be using your GitHub password to log in, but that's no longer possible. But you can still use check50 and submit50! See https://cs50.ly/github for instructions.
Make sure your username and/or personal access token are valid and check50 is enabled for your account. To enable check50, please go to https://submit.cs50.io in your web browser and try again. For instructions on how to set up a personal access token, please visit https://cs50.ly/github

What can I do?

**Comment by rongxin-liu** [comment]
Please make sure you have indeed entered your personal access token correctly (no leading/trailing spaces). If still having issues with check50, please email sysadmins@cs50.harvard.edu.
