### ISSUE TITLE
says "correctly" rather than "incorrectly"

### ISSUE THREAD

**Issue by yashpalgoyal1304** [cs50/check50#271]
### Summary
It says "handles correctly" even when the code fails the test 

### Details
* see the following report for example:  
https://submit.cs50.io/check50/0420c859c85191837118c8088df9eed20d65faf7
* screenshot: 
![image](https://user-images.githubusercontent.com/19423063/144715529-0338839e-600d-46c2-b15b-89e0e09ff989.png)

**Comment by rongxin-liu** [comment]
The frown face means the code fails the test "handles a height of 1 correctly".

**Comment by yashpalgoyal1304** [comment]
a part of me wants to suggest the following:

```
:) height of 0 == rejected
:( height of 1 == handled correctly
```

much more precise, but again, can be a bit cryptic for some 
similar to the compiler errors lol (ref: "Week 1: C" @ [41:22])

(though, shouldn't be ∵ `==` it's already communicated in lecture)

[41:22]: https://www.youtube.com/watch?v=zYierUhIFNQ&t=41m22s

**Comment by yashpalgoyal1304** [comment]
hi, was thinking about it, and yeah, the minimum viable solution (seriously this time) seems to be enclosing the tests in quotes.
so, for example:

```
:) "mario.c exists"
. 
.
.
:( "handles a height of 8 correctly"
:( "rejects a height of 9" , and then "accepts a height of 2"
. 
. 
.
```
