### ISSUE TITLE
Check50 'Mario More' Error

### ISSUE THREAD

**Issue by lewis-jardine** [cs50/check50#272]
When executing check50 on Pset1 'Mario More', it shows the Mario program has failed on multiple conditions. 
However, the 'Expected Output' and 'Actual Output' on these conditions are both identical, despite the program stating that it has failed and they are not. 
'did you add too much trailing whitespace to the end of your pyramid?' is given as a failure reason, however, no trailing whitespace on the actual output is present.

Please reference the below link to view the file output:
https://submit.cs50.io/check50/c13e01552e300202cf745b46d7aa632b9f53d838

```
:) mario.c exists
:) mario.c compiles
:) rejects a height of -1
:) rejects a height of 0
:( handles a height of 1 correctly
    expected ""#  #"", not ""#  #""
    did you add too much trailing whitespace to the end of your pyramid?
:( handles a height of 2 correctly
    expected "" #  #"\n"##  ...", not "" #  #"\n"##  ..."
    did you add too much trailing whitespace to the end of your pyramid?
:( handles a height of 8 correctly
    expected ""       #  #"\...", not ""       #  #"\..."
    did you add too much trailing whitespace to the end of your pyramid?
:( rejects a height of 9, and then accepts a height of 2
    expected "" #  #"\n"##  ...", not "" #  #"\n"##  ..."
    did you add too much trailing whitespace to the end of your pyramid?
:) rejects a non-numeric height of "foo" 
:) rejects a non-numeric height of "" 
```

This appears to be a bug with check50, however, if you see something that I have missed with my code please let me know!
Many thanks.

**Comment by rongxin-liu** [comment]
Please check if you have any extra characters at the end when printing each line of the pyramid.
