### ISSUE TITLE
cash.c is showing cash_test.c

### ISSUE THREAD

**Issue by yashpalgoyal1304** [cs50/check50#273]
* Here, on running `check50 cs50/problems/2022/x/cash` or even the `submit50` command, i am shown following error
* Link: https://submit.cs50.io/check50/e2cfa80efd6f5dbfd307ab07ce68e90e99bd4339
* It seems to be trying to compile `cash_test.c` while only `cash.c` is what i made. so... how can i ever fix that 😅 

+ Log

```log
:) cash.c exists
Log
checking that cash.c exists...

:( cash.c compiles
Cause
code failed to compile
Log
running clang cash.c -o cash -std=c11 -ggdb -lm -lcs50...
running clang cash_test.c -o cash_test -std=c11 -ggdb -lm -lcs50...
cash_test.c:94:1: warning: non-void function does not return a value [-Wreturn-type]
}
...
^
cash_test.c:219:26: warning: implicit declaration of function 'calculate_quarters' is invalid in C99 [-Wimplicit-function-declaration]
printf("%i", calculate
```

**Comment by rongxin-liu** [comment]
This is the way check50 to run the test on your code, and it seems that your code is missing the required method declaration. Please double-check on the problem set specification:
[https://cs50.harvard.edu/x/2022/psets/1/cash/](https://cs50.harvard.edu/x/2022/psets/1/cash/)

**Comment by rongxin-liu** [comment]
For all assignments related questions, please email [systemadmins@cs50.harvrad.edu](systemadmins@cs50.harvrad.edu)

**Comment by yashpalgoyal1304** [comment]
someone posted this on ED as well, so, sharing here just for future reference.

**Comment by rongxin-liu** [comment]
Thanks for posting. I'm afraid the student did not follow instructions and therefore failed the checks.

**Comment by yashpalgoyal1304** [comment]
Hi, so, i was thinking that maybe check50 should check and show a message, something like:

```
This seems like 2021's version for cash. Please update it according to 2022's version. 
Read more at https://cs50.harvard.edu/x/2022/psets/1/cash/ 
```

Adding the above message in check50's report will redirect to the 2022's version of cash which contains following clear instructions already. This will make things foolproof and hard to miss.

> CS50x 2022’s version of Cash is quite different than CS50x 2021’s version. It will be in your best interest to do this problem from scratch, if you do not have credit for the work you did in 2021. Last year’s version will fail to compile when checked by check50 due to the fact that in this new version, you must implement functions which the testing suite will test independently, beyond just checking for the final answer (as last year’s version did).
