### ISSUE TITLE
check50 fails to identify incorrect answer

### ISSUE THREAD

**Issue by yashpalgoyal1304** [cs50/check50#274]
### Prelude
* check50 seems to only check for the last digits of the answer
* while it worked fine for most cases for me
* i today stumbled upon a case where it failed

### Details
* see: the report of last 2nd test for cash 2022 "input of 41 cents yields output of 4 coins"
https://submit.cs50.io/check50/f7d7e6cd16245078b4dc91539036b4de10adab7c 
* i noticed that my cash-2021's answer "...164\n" was marked correct in cash-2022

Filling it as per:
> Discovering but failing to disclose to the course’s heads bugs in the course’s software that affect scores.
> _- clause 4 | [Not Reasonable < Academic Honesty](https://cs50.harvard.edu/x/2022/honesty/#not-reasonable)_

![vivaldi_wM8gBRIwVc](https://user-images.githubusercontent.com/19423063/148704367-11bb2d17-38a6-4dfe-b312-fffbd91ee2d6.png)

**Comment by rongxin-liu** [comment]
Thanks for reporting, but this is not related to check50 itself. Please open assignment related issues at: https://github.com/cs50/problems/issues

You can inspect the check here:
[https://github.com/cs50/problems/blob/2022/x/cash/__init__.py](https://github.com/cs50/problems/blob/2022/x/cash/__init__.py)

The check was not looking for the last digit of the answer, and your program was outputting more information than we've asked for:
[https://cs50.harvard.edu/x/2022/psets/1/cash/](https://cs50.harvard.edu/x/2022/psets/1/cash/)

Mind following the instruction exactly and try again?

**Comment by goyalyashpal** [comment]
sir,

as for this issue not being related to check50, i am very sorry. to avoid duplicates, can u move the issue to that repo?? https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

other than that, for sure, there were more lines of output before. but for the last line, my program was outputting the answer "164", and that was marked correct.

you can try running it locally, and see yourself if that will help with testing out stuff.

i can trim that extra output, and my judgement says that it will still show it correct.
the other ways to test it can be:
* with program tailor made just for that case using if statement, and printing "xxx4" there, where xxx are the digits on left side of the number

umh, i dont know how to explain it better :(
