### ISSUE TITLE
Getting "undefined reference to `get_string'" error despite having included cs50.h

### ISSUE THREAD

**Issue by E-Nkosi** [cs50/check50#277]
I'm just starting with Week 2's problem set, in this case readability and can't get past this first step  I get this error message /usr/bin/ld: /tmp/cc7uIkNX.o: in function `main': hello.c:(.text+0x1e): undefined reference to `get_string'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: hello] Error 1

Is the VISUAL STUDIO CODE environment somehow different in how we include the functions in those libraries? I used #include <cs50.h> etc. above the int main(void), so I don't understand why the get_string function is being flagged as undefined. I'm using the cloud based version of VS Code.

**Comment by dmalan** [comment]
If using [code.cs50.io](https://code.cs50.io/), be sure to compile your code with `make` rather than `clang` directly!

**Comment by E-Nkosi** [comment]
Thank you. It worked but now I receive this error message..been stuck for almost 2 days now.

 warning: implicit declaration of function ‘get_string’; did you mean ‘GetString’? [-Wimplicit-function-declaration]
    7 |     string answer = get_string ("What's your name?");
      |                     ^~~~~~~~~~
      |                     GetString
hello.c:7:21: warning: initialization of ‘string’ {aka ‘char *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
/usr/bin/ld: /tmp/ccPESgLi.o: in function `main':
hello.c:(.text+0x1c): undefined reference to `get_string'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: hello] Error 1

**Comment by rongxin-liu** [comment]
Could you please email your code and screenshots of errors to [sysadmins@cs50.harvard.edu](sysadmins@cs50.harvard.edu)

**Comment by rongxin-liu** [comment]
> Thank you. It worked but now I receive this error message..been stuck for almost 2 days now.
> 
> warning: implicit declaration of function ‘get_string’; did you mean ‘GetString’? [-Wimplicit-function-declaration] 7 | string answer = get_string ("What's your name?"); | ^~~~~~~~~~ | GetString hello.c:7:21: warning: initialization of ‘string’ {aka ‘char *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion] /usr/bin/ld: /tmp/ccPESgLi.o: in function `main': hello.c:(.text+0x1c): undefined reference to `get_string' collect2: error: ld returned 1 exit status make: *** [: hello] Error 1

And how did you compile your code exactly? Did you run `make hello` or using `clang` command? If using `clang` command, please be sure to also link cs50's library.
