### ISSUE TITLE
add clean way of factoring out CFLAGS to a term-specific config file

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#29]
E.g., should avoid hardcoding compilation lines like `self.spawn("clang -o resize resize.c -lcs50").exit(0)`, since we tend to tweak `CFLAGS` each year. Ideal to factor that var out so that, on a per-semester basis, it can be configured to match the IDE. Else we'll have to grep through checks each year tweaking, which doesn't feel ideal? Perhaps we should just add a `.clang` check that wraps `.spawn`?

**Comment by dmalan** [comment]
Actually, given that we handle compilation in a `.compiles` check already, maybe this adds undue complexity. Changing the command-line args to `clang` once per year, by checking each check, might not be that onerous. What do you think, @hljames, @crossroads1112, @brianyu28?

**Comment by crossroads1112** [comment]
This has been addressed, I think, `check50.c.compile` in v3
