### ISSUE TITLE
Error in check50

### ISSUE THREAD

**Issue by riasharma24** [cs50/check50#298]
Hello, my code is working just fine and is generating the desired output also, still check50 is generating an error, and i cannot really interpret it
![Screenshot (5)](https://user-images.githubusercontent.com/102987340/218308482-8d11bd35-c102-4037-952c-2bb9d42986bb.png)

**Comment by rongxin-liu** [comment]
Please post assignment-related questions on Ed or Discord:
https://cs50.harvard.edu/x/2023/communities/
