### ISSUE TITLE
CS50P pset0 Faces

### ISSUE THREAD

**Issue by RexRowan** [cs50/check50#299]
This keeps on showing up no matter how I change my code:  bash syntax error near unexpected token `)' 

There's nothing wrong with any version of my code. I even used backslashes before the emoticons' ')' and '(', same error message.

Please test it with your solution and see if it gets the same result, thanks.

**Comment by dmalan** [comment]
Sounds like a bug or usage error, I'm afraid! Best to post in any of CS50's communities!

https://cs50.harvard.edu/x/2023/communities/

**Comment by RexRowan** [comment]
Sorry, nothing wrong with the code, I forgot to run the interpreter is all! My bad lol 😂
