### ISSUE TITLE
check 50 returns an error - bash: check: command not found

### ISSUE THREAD

**Issue by SofiaSchramm** [cs50/check50#304]
Hi there,
Does anyone know what I am doing wrong.
Thanks

**Comment by rongxin-liu** [comment]
Are you running the command "check50" on cs50.dev (Codespace)? Can you attach a screenshot of the issue here?

**Comment by SofiaSchramm** [comment]
> 

I am using vs code on my computer. I have done the population lab
This is what I tried:

**Comment by SofiaSchramm** [comment]
![CodeSnip](https://github.com/cs50/check50/assets/87720574/5cf63d09-8835-4a05-8c9f-fa3603877404)

**Comment by SofiaSchramm** [comment]
![CodeSnip](https://github.com/cs50/check50/assets/87720574/b16b9896-70b2-44b6-86aa-59af413ad3d6)

**Comment by rongxin-liu** [comment]
The command is "check50", not "check 50". There is no space between "check" and "50".

**Comment by Lea976** [comment]
> The command is "check50", not "check 50". There is no space between "check" and "50".

hii 
I'm having a submission issue may you please help me out

**Comment by Lea976** [comment]
> Please email [sysadmins@cs50.harvard.edu](mailto:sysadmins@cs50.harvard.edu).
> 
> Thanks!

thank you @rongxin-liu !

**Comment by Lea976** [comment]
thank you so much! l just did
