### ISSUE TITLE
submitting issue

### ISSUE THREAD

**Issue by Lea976** [cs50/check50#306]
hi guys,
so i ran:
 submit 50 cs50/labs/2023/x/population
in the lab1 terminal.
I was asked to insert a personal github token; I did that , but it said I'm probably still logging in with my password and can use check50 or submit50 instead, tried that but these 2 latters seemed as much longer processes with many files to download.
Any help would be appriciated, thanks for stopping by <3

**Comment by rongxin-liu** [comment]
Are you using cs50.dev? Can you please email sysadmins@cs50.harvard.edu with a screenshot of the issue?

Thank you.

**Comment by Lea976** [comment]
> Are you using cs50.dev? Can you please email [sysadmins@cs50.harvard.edu](mailto:sysadmins@cs50.harvard.edu) with a screenshot of the issue?
> 
> Thank you.

![Screenshot (2)](https://github.com/cs50/check50/assets/135071368/ae48a169-3bf6-48dd-9d8f-75447e9cbc11)

 @rongxin-liu thank you so much , ill do that.

**Comment by Lea976** [comment]
hii is it normal not to find my certificate anywhere after a few days of making the purchase cause it's Dec. 30 already and I'm really worried.
