### ISSUE TITLE
pip3 install check50 doesn't work

### ISSUE THREAD

**Issue by ArdB01** [cs50/check50#311]
I wanted to install check50 and in their website it tells to type 'pip3 install check50' I did that but I got this error.

<img width="596" alt="Screenshot 2023-07-31 at 23 59 44" src="https://github.com/cs50/check50/assets/139978263/da801404-31b3-4dc9-84fb-e696e2d4977b">

**Comment by rongxin-liu** [comment]
Thanks for repoint. Please attached the full error here and let us know what operating system you are using.

**Comment by ArdB01** [comment]
Iam using macOS Ventura 13.2.1

Rongxin Liu ***@***.***>, 1 Ağu 2023 Sal, 00:13 tarihinde
şunu yazdı:

**Comment by ArdB01** [comment]
> Thanks for reporting. Please attached the full error here and let us know what operating system you are using.

Iam using macOS Ventura version 13.2.1
<img width="1246" alt="Screenshot 2023-08-01 at 00 57 06" src="https://github.com/cs50/check50/assets/139978263/b21a860a-201e-41f4-ab5c-73104a773db3">
<img width="1252" alt="Screenshot 2023-08-01 at 00 57 24" src="https://github.com/cs50/check50/assets/139978263/390763b1-84c8-474d-9ecc-c05917e57f97">
<img width="1243" alt="Screenshot 2023-08-01 at 00 57 42" src="https://github.com/cs50/check50/assets/139978263/0ccd6e75-a5f5-4850-b74d-7104bc4d1149">

**Comment by karjallo** [comment]
Same error in ArchLinux, and also with submit50.

**Comment by ArdB01** [comment]
Yeah I also got the same error with submit50.

**Comment by livingst76** [comment]
> Yeah I also got the same error with submit50.

I experienced this too. I'm new to Computer Programming and I don't what some of the errors mean either.

**Comment by rongxin-liu** [comment]
We have released a new version of check50 that should address this issue.

Please run `pip3 install check50 --upgrade` to install check50 and see if that works.

**Comment by ArdB01** [comment]
> `pip3 install check50 --upgrade`


https://github.com/cs50/check50/assets/139978263/84151291-9a7d-4a59-8fb1-f960df7c9262

It works now but here is an other problem with github I think.

**Comment by ArdB01** [comment]
> > `pip3 install check50 --upgrade`
> 
> Screen.Recording.2023-08-01.at.18.03.20.mov
> 
> It works now but there is an other problem with github I think.

Now it works perfectly. Thanks
