### ISSUE TITLE
check50 is taking longer than normal! PSET 2

### ISSUE THREAD

**Issue by VincentVu14072000** [cs50/check50#313]
I am doing my wordle problem set 2 and when I want to use check 50, it times out.
It provides a link to submit.cs50.io but the page is 404 NOT FOUND.
Please help!

**Comment by rongxin-liu** [comment]
I'm sorry, there is an on-going GitHub incident that causes the issue:
https://www.githubstatus.com/incidents/rk1918knvr0w
