### ISSUE TITLE
CS50P/PSET4/Bitcoin

### ISSUE THREAD

**Issue by alitaraghi** [cs50/check50#316]
The api responded to different prices due to time but check50 has a constant value (37817.3283) and doesn't change it 

This video shows problem :

https://github.com/cs50/check50/assets/46902486/36482fa5-6432-4d78-87ac-d02fcb55d734

**Comment by rongxin-liu** [comment]
Thanks for reporting, but our check50 on this problem set doesn't rely on live data. I'd suggest you double-check your implementation.
