### ISSUE TITLE
allow `.xhtml` file extension / `application/xhtml+xml` mimetype in checks

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/check50#324]
hi! thanks again for such a wonderful package of course.

### titles/summaries

* allow `.xhtml` file extension / `application/xhtml+xml` mimetype in checks

### details

* i was thinking if you would consider allowing `xhtml` 5 (that is `html` 5 with strictness of xml).
* `xhtml` is awesome as in it, a syntax error raises a very clear error - similar to a normal programming language. rather than resulting in an undefined & hence inconsistent output.
* for the records, `xhtml` 5 is fully compatible with `html` 5;[^xhtml-w3c.org] there's no long weird doctype declarations, or any syntactic differences

[^xhtml-w3c.org]: see citations in the immediately following comment

<details><summary><h3>references in cs50 code</h3></summary>

#### for checks directly operating on files (like `homepage`):

* https://github.com/cs50/problems/blob/0ef111978b78da7f2323daad035d921e58f4b849/homepage/.cs50.yml#L1-L3

#### for flask related psets (like `finance`)

* https://github.com/cs50/check50/blob/c9d3d2e06d52f059ee9a8d03fdf3d1aa85e160ef/check50/flask.py#L120-L125

* it seems that the call to this function `content()` in case of pset-`finance` is done in this `Flask.validate_form()` method: 
https://github.com/cs50/problems/blob/0ef111978b78da7f2323daad035d921e58f4b849/finance/__init__.py#L182

</details>

<details><summary><h3>attachments</h3></summary>

only cs50 staff would be able to access contents of these (as these relate to me50 organization):

* source code (was not meant as submission)
https://github.com/me50/goyalyashpal/tree/2f5d3bb60081564f9fd484600219c1bbb961532a

* corresponding `submit50` report:
https://submit.cs50.io/check50/83f6044cc71e1e3ea196a0ac6b8acfea4660b107

### screenshots:

* ![image](https://github.com/cs50/check50/assets/19423063/bf44270c-0896-4ac3-bd18-87eb8a87f6f8)

</details>

**Comment by dmalan** [comment]
We used to use XHTML, actually, but the world never really latched on. E.g., according to one measure, https://w3techs.com/technologies/details/ml-xhtml_transitional. Much as the idea resonates, then, we indeed only teach/expect HTML5 now!

**Comment by goyalyashpal** [comment]
yeah, it's kinda surprising that xhtml adoption stayed low.

but reassuring things in that regard seems that 
* xhtml5 is now in complete reconciliation with html5, infact, it's now just an XML-serialized HTML5
* there're no conflicting versions of latest standard html[^whatwg-w3c] only since 2019
which is fairly recent in context of such all encompassing "standards"

in contrast, in earlier XHTMLs (even upto XHTML 1.1 or XHTML 2):
* various modern tags or attributes from HTML were completely missing; 
* XHTML2 was planned to be entirely separate thing on its own
* so, using XHTML came at a _significant_ cost of missing out of all the standard things html offers

that significant penality is not there now, so, i expect that those wanting to use it can use it freely - which may slowly cause it to finally catch on now.




[^whatwg-w3c]: [cite] The two entities [WHATWG and W3C] signed an agreement to work together on a single version of HTML on 28 May 2019.[[54]](https://en.wikipedia.org/wiki/HTML5#cite_note-54)

----
on the same line, the shared page from w3techs: 
* doesn't seem to track XHTML5, 
* as all the listed XHTML versions there (transitional, strict, basic, +RDFa, mobile) are old, 
* which makes me wonder if they are using the old XHTML DTDs (which are no longer required) to detect the usage 
(old DTDs like: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">`) 

<img src="https://github.com/cs50/check50/assets/19423063/a295700d-24ed-4c47-b828-6a3bf3755ef0" width=500px />


----

**Comment by goyalyashpal** [comment]
anyhow, i respect your decision 😃 

thanks a lot for prompt response as well, 

wish me luck in finally completing cs50 before new year this month lol 😆
