### ISSUE TITLE
Check50 fails due to segmentation error for all tasks of CS50 Python Problem Set 5

### ISSUE THREAD

**Issue by KurayiChawatama** [cs50/check50#326]
I'm(and others in the community too) experiencing a recurring issue with check50 for pset5 today, where I encounter a segmentation fault consistently for all problems, even though I successfully submitted tests a few days ago. I have not made any changes to the code or test cases since the last successful submission. The segmentation fault occurs across all problems in the set, and the error persists despite passing the same tests previously. I appreciate your prompt assistance in resolving this matter.

**Comment by rongxin-liu** [comment]
Thanks, done.
