### ISSUE TITLE
Check50 is checking the wrong code

### ISSUE THREAD

**Issue by WDYC2003** [cs50/check50#331]
I want to check an assignment using check50, but it keeps checking a different code for a different assignment. How can I correct this?

**Comment by rongxin-liu** [comment]
Can you please describe the issue in detail and attach screenshots?

**Comment by WDYC2003** [comment]
![image](https://github.com/cs50/check50/assets/94567618/9193f033-f98a-4099-982d-398cf59e972b)
I want the code to check name.c, but it keeps checking hello.c. This wasn't an issue with the other assignments, they were both verified normally.

**Comment by rongxin-liu** [comment]
Thanks for attaching the screenshot.

This wasn't a check50 issue and the check50 check is indeed looking for `hello.c`, not `name.c`.
