### ISSUE TITLE
check50 does not allow me to enter my access token at the command line in VS code. 

### ISSUE THREAD

**Issue by ayushm64** [cs50/check50#332]
I have been having issues with check50. When I run check50 at the command line, this is what is printed to the terminal: 

____________
Connecting.....
Authenticating...
GitHub now requires that you use SSH or a personal access token instead of a password to log in, but you can still use check50 and submit50! See https://cs50.ly/github for instructions if you haven't already!
Verifying....
You might be using your GitHub password to log in, but that's no longer possible. But you can still use check50 and submit50! See https://cs50.ly/github for instructions.
Make sure your username and/or personal access token are valid and submit50 is enabled for your account. To enable submit50, please go to https://submit.cs50.io in your web browser and try 
again. For instructions on how to set up a personal access token, please visit https://cs50.ly/github
____________

Previously, I would be asked to enter my github username and then the personal access token that I have configured. I tried uninstalling and reinstalling check50 using pip, deleting and creating a new personal access token, and revoking and re-granting check50 permissions in my github OAuth application settings. None of these have been successful. If it's relevant, when I try to use submit50 a message is printed to the terminal that simply says "submission cancelled".

**Comment by rongxin-liu** [comment]
Please email sysadmins@cs50.harvard.edu with a screenshot of the issue and indicate on which platform you were running check50.
