### ISSUE TITLE
Simple mathematical bug on check50

### ISSUE THREAD

**Issue by djig0889** [cs50/check50#335]
Well you just need to type in

#include <cs50.h>
#include <stdio.h>

int main(void)
{
    char c = '#';
    int a;
    do
    {
        a = get_int("Size of pyramid: ");
    }
    while ( a > 8  || a < 1 );

    int n = 1;
    int k = a + 1;

    for (int i = -(2 * a) + 2; i < a; i++)
    {
        for (int j = 1; j < a; j++)
        {
            printf(" ");
        }
        while (a < k)
        {
            printf("#");
            k--;
        }
        a--;
        k = k + n;
        n++;
        printf ("\n");

        if (a <= 0)
        {
            k = a;
        }
    }
}
And then check with the check50, and it will say that it can´t handle the input 8, and then it will show me the correct output and my output, and they are exactly the same but it keeps showing me that is incorrect.

**Comment by dmalan** [comment]
Afraid it's a bug in your code! Though for questions on problem sets, best to post in any of CS50's communities, https://cs50.harvard.edu/x/communities/, so that any of us can answer! Or you can ask the duck at [cs50.ai](http://cs50.ai/)!

**Comment by djig0889** [comment]
> Afraid it's a bug in your code! Though for questions on problem sets, best to post in any of CS50's communities, https://cs50.harvard.edu/x/communities/, so that any of us can answer! Or you can ask the duck at [cs50.ai](http://cs50.ai/)!

Thanks for the help now its working properly.
