### ISSUE TITLE
Error importing cs50 method in Python

### ISSUE THREAD

**Issue by PrackSoft** [cs50/check50#336]
Hi, I am doing Lecture 6 (2023) and can import cs50 method with the following code:

from cs50 import get_int

height = get_int("Height: ")

ImportError: cannot import name 'MappingProxyType' from 'types' (/workspaces/138399398/w6Lecture/types.py)

**Comment by rongxin-liu** [comment]
Please rename your `types.py` file to something else. Thanks!

**Comment by PrackSoft** [comment]
Hi, rongxin-liu:

I have a trouble and don not find how to open a discussion or where to make a post about it.

There are some issues with the VSC, and when I loged in today I found that there are some missing folders that am working on to finish my CS50 course.

I already ask for help at the technical support, but may be you know how to proceed in this case.

If it helps, I know that there are three folders lost, at least: finance; project; TWT

Thank you and sorry to bother you. Have a great day
