### ISSUE TITLE
add .get and .post methods that wrap driver's, adding HTTP status code and headers to response

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#34]
If possible, since https://github.com/cs50/check50/pull/18#discussion_r128884638. Ideally with base URL baked in so you can call with just, e.g., `self.get("/foo")`.

**Comment by crossroads1112** [comment]
This does not appear to be possible: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141

**Comment by dmalan** [comment]
Even if not part of Selenium's API, not possible to pull from the
underlying PhantomJS driver?

**Comment by brianyu28** [comment]
Per chat with Patrick, closing.
