### ISSUE TITLE
bash./ permission denied

### ISSUE THREAD

**Issue by Ortega1299** [cs50/check50#345]

**Comment by Ortega1299** [comment]
it will let me make a code but wont let me run my code and i do have #include <cs50.h> and #include <stdio.h> what am i doing wrong?

**Comment by dmalan** [comment]
For CS50 questions, best to post in any of CS50's communities, https://cs50.harvard.edu/x/communities/! Or you can ask the duck at [cs50.ai](http://cs50.ai/)!
