### ISSUE TITLE
check50 ran into error while running checks on 2024/x/movies problem

### ISSUE THREAD

**Issue by sam-uz** [cs50/check50#347]
Not able to use check50 on the movies problem. It is working fine for other problems. I also submitted movies, but still there were no grades on that submission and it also wasn't reflected in the gradebook.

![Screenshot 2024-09-07 130321](https://github.com/user-attachments/assets/fe21f397-2425-40b0-8c42-7ae0d8b28a9e)
![Screenshot 2024-09-07 130104](https://github.com/user-attachments/assets/3d2e3d53-2d52-4bc5-aaf1-e25ba2f68c02)
![Screenshot 2024-09-07 130041](https://github.com/user-attachments/assets/690a27e5-b484-4d9a-8d59-39d9eb922f16)

PS: My first time reporting on GitHub so don't know what the proper procedure is. However, I went through previous reported issues to the best of my ability and haven't found this particular issue on there. Sorry if this is already reported.

**Comment by rongxin-liu** [comment]
Thanks for reporting. For issues like these, please email sysadmins@cs50.harvard.edu.
