### ISSUE TITLE
pset3 check50 can fail code that actually works!

### ISSUE THREAD

**Issue by antonylewis** [cs50/check50#57]
Hi, it's really great that students can see the check50 code.
For this file https://github.com/cs50/check50/blob/pset3/checks/cs50/2017/x/fifteen/checks.py
check50 overwrites the draw() function of the student.  This causes errors if the student is tracking the blank cell in her draw() function.
See: https://cs50.stackexchange.com/questions/26421/pset3-fifteen-c-passes-local-tests-but-fails-check50-with-timeouts/26422
Suggest not overwriting the draw() function and perhaps looking at the log file (and logging invalid attempts?)
Thanks for a really great course!

**Comment by crossroads1112** [comment]
Hey Antony, thanks for letting us know! The specification will be changing for next year's course to mandate that `draw` have no side effects (which is better design anyway). I'll fix the checks for this year though!

Kudos for digging through the source! For future reference, the checks have moved to [cs50/checks](https://github.com/cs50/checks) so any changes will be made there.

**Comment by antonylewis** [comment]
Thank you for getting back so quickly!  I guess when you make your change,
my stackoverflow question will be no longer relevant :)

Thanks for the link, and thank you again for enabling broad access to a
fantastic course!

Kind regards

Antony

Antony Lewis
+65 9296 4222
Skype: antonylewis
Tweet: @antony_btc
Blog: www.bitsonblocks.net

**Comment by crossroads1112** [comment]
Closing since `fifteen` has been replaced by `music`.
