### ISSUE TITLE
"See <URL> for more detail." after submission, but the URL doesn't contain any results.

### ISSUE THREAD

**Issue by alchermd** [cs50/check50#60]
***Problem Set 1: C - Mario (More)***

Screenshots: 

1. **CS50 IDE CLI**

![](http://i.imgur.com/okqDJ79.png)

2. **Check50 Page**

![](http://i.imgur.com/F761GAe.png)

**Comment by alchermd** [comment]
UPDATE: I've submitted `mario.c` and it doesn't appear to be graded in my gradebook page.

![](http://i.imgur.com/USJcZ8p.png)

**Comment by curiouskiwi** [comment]
@brianyu28 After looking at the code,  the test for `height = -1` should fail.  Wonder if there is a problem with that particular test such that, when the overall results are displayed, it breaks.

**Comment by kzidane** [comment]
Hi @alchermd, mind trying to resubmit your solution see if the issue still exists, please? Thank you!

**Comment by curiouskiwi** [comment]
@kzidane He fixed his program and resubmitted it to get a grade. I'll test his old code for you.

**Comment by kzidane** [comment]
Per @curiouskiwi the issue was fixed. Thank you for reporting (and @curiouskiwi for confirming!) Let us know if you need further assistance!

**Comment by Haatveit88** [comment]
I am having the exact same behaviour, but I'm on pset3/find (more comfortable). I looked up all the tests in the source, and I've run those tests by hand in the IDE, and the code works fine and returns results just as expected, so I can't really figure out why check50 returns blank. I tried submitting, and get a blank/5 score.

Should I open a new issue?
