### ISSUE TITLE
Debugging checks should be easier

### ISSUE THREAD

**Issue by tlively** [cs50/check50#77]
Instead of just printing "check50 ran into an error while running checks!", it would be great if errors were allowed to propagate when run with --verbose. It would also be nice to have a `self.info` function for checks that could be used to print debug messages with --verbose.

**Comment by crossroads1112** [comment]
Am thinking `--verbose` should just imply `--log` as well (which will show any exceptions thrown by the check). Does `--log` satisfy the use case you have in mind, or do you think there's still reason to add `self.info` or similar?

**Comment by crossroads1112** [comment]
`--verbose` now does imply `--log`.
