### ISSUE TITLE
Enhancement - install java compiler to add java support for check50

### ISSUE THREAD

**Issue by jake23hogs** [cs50/check50#98]
During the CS50 teacher workshop I've been trying to implement java checks in the check50 and submit50 repos. I think I have correctly implemented the checks, but I believe that a java compiler is missing from the server that is running check50. Below is the link to my java checks. 
We think they will work if a java compiler is installed. I hope it's as simple as the following command sudo apt-get install openjdk-9-jdk-headless

You can run this in the cs50 IDE : 
check50 cs50/2017/x/isPrime/java@jake23hogs/checks

Link to repo:
https://github.com/jake23hogs/checks/tree/master/cs50/2017/x/isPrime/java

**Comment by crossroads1112** [comment]
Thanks for the heads up! @kzidane should be able to add `javac` to the Docker image.

**Comment by jake23hogs** [comment]
Awesome! Thanks for passing it along!

**Comment by kzidane** [comment]
https://github.com/cs50/ecs/pull/15

**Comment by pazz** [comment]
FYI, I have written a small extension for check50 that wraps around the java compiler/interpreter and also allows to run junit5 unit tests (which can raise check50 exceptions when junit asserts fail).
The code is [here](https://github.com/pazz/check50_java), and the extension is [on pypi as `check50-java`](https://pypi.org/project/check50-java).
